# This is a basic workflow to help you get started with Actions

name: CodeQL

on:
  pull_request:
    
  workflow_dispatch:

jobs:
 
  aly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go
      
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
      
