# This is a basic workflow to help you get started with Actions

name: CodeClimate_PR_Comment

on:
  pull_request:

jobs:
  PR_Comment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
#         env:
#           CID: ${{ github.sha }}
#           PULL_NUMBER: ${{ github.event.pull_request.number }}
#           OWNER: ${{ github.repository_owner }}
#           REPO: ${{ github.event.repository.name }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const state_urls = context.payload.pull_request.statuses_url.split('/')
            const commit_id = state_urls[state_urls.length -1]
            const owner = context.payload.repository.full_name.split('/')[0]
            const repo = context.payload.repository.full_name.split('/')[1]
            console.log(context)
            github.request('POST /repos/{owner}/{repo}/pulls/{pull_number}/comments', {
              owner: owner,
              repo: repo,
              pull_number: context.payload.pull_request.number,
              body: 'Great stuff!',
              commit_id: commit_id,
              path: 'main.go',
              start_line: 10,
              start_side: 'RIGHT',
              line: 11,
              side: 'RIGHT'
            })
            let info = await github.rest.pulls.get({
              owner: owner,
              repo: repo,
              pull_number: context.payload.pull_request.number,
            });
            console.log(info)
      
      # GitHub CLI api
#       - name: Add comment to PR
#         run: | 
#           gh api --method POST -H "Accept: application/vnd.github.v3+json" repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pulls/${{ github.event.pull_request.number }}/comments -f body='Great stuff!' -f path='main.go' -F start_line=10 -f start_side='RIGHT' -F line=11 -f side='RIGHT'
#         env:
#           CID: ${{ github.sha }}
#           PULL_NUMBER: ${{ github.event.pull_request.number }}
#           OWNER: ${{ github.repository_owner }}
#           REPO: ${{ github.event.repository.name }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

