# This is a basic workflow to help you get started with Actions

name: CodeClimate_PR_Comment

on:
  pull_request:

jobs:
  PR_Comment:
    runs-on: ubuntu-latest

    steps:
#       - uses: actions/checkout@v3
#         with:
#           ref: ${{ github.base_ref }}
      
#       - run: echo BASE=`git rev-parse HEAD` >> $GITHUB_ENV
          
#       - uses: actions/checkout@v3
      
      - name: diff info get
        run: |
          echo '51,10,262,0,57,"(anonymous)@18-74@./dev/firebase/functions/src/index.ts","./dev/firebase/functions/src/index.ts","(anonymous)","(anonymous)",18,74' > sample.csv
          echo "SAMPLE=`cat sample.csv`" >> $GITHUB_ENV
          
      
      - uses: actions/github-script@v6    
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const state_urls = context.payload.pull_request.statuses_url.split('/')
            const commit_id = state_urls[state_urls.length -1]
            const owner = context.payload.repository.full_name.split('/')[0]
            const repo = context.payload.repository.full_name.split('/')[1]
            const pull_number = context.payload.pull_request.number
            const {SAMPLE} = process.env
            console.log(`${SAMPLE}`)
            
            let pull_info = await github.request('GET /repos/{owner}/{repo}/pulls/{pull_number}/files', {
              owner: owner,
              repo: repo,
              pull_number: pull_number
            })
            
            let file = pull_info.data[0].filename
            
            try {
              await github.request('POST /repos/{owner}/{repo}/pulls/{pull_number}/comments', {
                owner: owner,
                repo: repo,
                pull_number: pull_number,
                body: 'Great stuff!',
                commit_id: commit_id,
                path: file,
                start_line: 1,
                start_side: 'RIGHT',
                line: 2,
                side: 'RIGHT'
              })
            } catch (error) {
              console.log(error)
            }
            console.log(pull_info)
          

