# This is a basic workflow to help you get started with Actions

name: CodeClimate_PR_Comment

on:
  pull_request:

jobs:
  PR_Comment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
#         env:
#           CID: ${{ github.sha }}
#           PULL_NUMBER: ${{ github.event.pull_request.number }}
#           OWNER: ${{ github.repository_owner }}
#           REPO: ${{ github.event.repository.name }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const state_urls = context.payload.pull_request.statuses_url.split('/')
            const commit_id = state_urls[state_urls.length -1]
            const owner = context.payload.repository.full_name.split('/')[0]
            const repo = context.payload.repository.full_name.split('/')[1]
            const pull_number = context.payload.pull_request.number
            let pull_info = await github.request('GET /repos/{owner}/{repo}/pulls/{pull_number}/files', {
              owner: owner,
              repo: repo,
              pull_number: pull_number
            })
            let file = pull_info.data[0].filename
            await github.request('POST /repos/{owner}/{repo}/pulls/{pull_number}/comments', {
              owner: owner,
              repo: repo,
              pull_number: pull_number,
              body: 'Great stuff!',
              commit_id: commit_id,
              path: file,
              start_line: 1,
              start_side: 'RIGHT',
              line: 2,
              side: 'RIGHT'
            })
            console.log(pull_info)
          

