# This is a basic workflow to help you get started with Actions

name: CodeClimate_PR_Comment

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # GitHub CLI api
      - name: Add comment to PR
        run: | 
          gh api --method POST -H "Accept: application/vnd.github.v3+json" repos/$OWNER/$REPO/pulls/$PULL_NUMBER/comments -f body='Great stuff!' -f commit_id='${{ github.sha }}'   
        env:
          PULL_NUMBER: ${{ github.event.pull_request.number }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
